Repository SkillsFundingAgency/das-qna-api, pull requests merged in 2019-12, with the labels that each got.

#156 Save answers refactor
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/FindNextRequiredActionTests/FindNextRequiredActionTestsBase.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/FindNextRequiredActionTests/When_next_page_has_a_NotRequiredCondition.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/FindNextRequiredActionTests/When_next_page_has_no_NotRequiredConditions.cs
  src/SFA.DAS.QnA.Application/Commands/Files/UploadFile/SubmitPageOfFilesHandler.cs
  src/SFA.DAS.QnA.Application/Commands/SetPageAnswers/SetAnswersBase.cs
  src/SFA.DAS.QnA.Application/Commands/SetPageAnswers/SetPageAnswersHandler.cs
  src/SFA.DAS.QnA.Application/Commands/SkipPage/SkipPageBySectionNoHandler.cs
  src/SFA.DAS.QnA.Application/Commands/SkipPage/SkipPageHandler.cs
Labels: Ready for Release, Tested

#144 APR-970 update copy in trading history pages
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section1.3.json
Labels: Blocked By Testers

#159 QnA validation enhancements
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/SetPageAnswersTests/When_answer_doesnt_relate_to_a_question.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/SetPageAnswersTests/When_incorrect_amount_of_answers_specified.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/SetPageAnswersTests/When_page_allows_multiple_answers.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/SetPageAnswersTests/When_page_contains_fileupload_question.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/SetPageAnswersTests/When_page_contains_only_fileupload_questions.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/SetPageAnswersTests/When_page_not_found.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/SubmitPageOfFilesHandlerTests/SubmitPageOfFilesTestBase.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/SubmitPageOfFilesHandlerTests/When_page_allows_multiple_answers.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/SubmitPageOfFilesHandlerTests/When_page_contains_mixture_of_question_types.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/SubmitPageOfFilesHandlerTests/When_page_not_found.cs
  src/SFA.DAS.QnA.Application.UnitTests/SFA.DAS.QnA.Application.UnitTests.csproj
  src/SFA.DAS.QnA.Application/Commands/Files/UploadFile/SubmitPageOfFilesHandler.cs
  src/SFA.DAS.QnA.Application/Commands/SetPageAnswers/SetPageAnswersHandler.cs
Labels: Awaiting PO Review

#164 APR-1132 code and json added
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/SetPageAnswersTests/When_a_branching_condition_is_question_tag.cs
  src/SFA.DAS.QnA.Application/Commands/SetPageAnswers/SetAnswersBase.cs
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section1.1.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section6.2.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section6.3.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section6.4.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section6.5.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section6.6.json
Labels: Tested

#102 APR-791 Evaluating Apprenticeship Training
  src/SFA.DAS.QnA.Database/projects/roatp/project.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section8.1.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section8.2.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section8.3.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section8.4.json
Labels: Awaiting PO Review

#149 APR-1107 : Show Complaints Web link page when website retrieved from UKRLP
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section5.3.json
Labels: Tested

#165 APR-793 criminal and compliance checks
  src/SFA.DAS.QnA.Database/projects/roatp/project.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section3.1.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section3.2.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section3.3.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section3.4.json
Labels: Tested
