Repository SkillsFundingAgency/das-qna-api, pull requests merged in 2020-02, with the labels that each got.

#195 Apr 1199 fha exemptions
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section1.5.json
Labels: Tested

#219 APR-1278 - Create endpoint to Snapshot an Application Data and Files
  src/SFA.DAS.QnA.Api.Client/SFA.DAS.QnA.Api.Client.csproj
  src/SFA.DAS.QnA.Api.Types/CreateSnapshotResponse.cs
  src/SFA.DAS.QnA.Api.Views/SFA.DAS.QnA.Api.Views.csproj
  src/SFA.DAS.QnA.Api/Controllers/ApplicationSnapshotController.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/CreateSnapshotTests/CreateSnapshotTestBase.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/CreateSnapshotTests/When_application_exists.cs
  src/SFA.DAS.QnA.Application.UnitTests/CommandsTests/CreateSnapshotTests/When_application_not_found.cs
  src/SFA.DAS.QnA.Application/Commands/CreateSnapshot/CreateSnapshotHandler.cs
  src/SFA.DAS.QnA.Application/Commands/CreateSnapshot/CreateSnapshotRequest.cs
  src/SFA.DAS.Qna.Api.Types/SFA.DAS.Qna.Api.Types.csproj
Labels: Ready for Release

#239 deadlock_test
  src/SFA.DAS.QnA.Api/Startup.cs
Labels: Do Not Merge

#240 APR-1349 Activate Pages Fixes
  src/SFA.DAS.QnA.Application/Commands/ResetPageAnswers/ResetPageAnswersHandler.cs
  src/SFA.DAS.QnA.Application/Commands/SetPageAnswers/SetAnswersBase.cs
  src/SFA.DAS.QnA.Application/Commands/SetPageAnswers/SetPageAnswersHandler.cs
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section1.5.json
Labels: Private Beta, Requires testing

#246 Qna superbranch
  src/SFA.DAS.QnA.Database/projects/roatp/ApplicationDataSchema.json
  src/SFA.DAS.QnA.Database/projects/roatp/project.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section0.1.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section1.1.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section1.2.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section1.3.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section1.4.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section1.5.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section2.1.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section2.2.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section2.3.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section3.2.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section3.4.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section4.1.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section4.2.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section4.3.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section4.4.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section4.5.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section4.6.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section5.1.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section5.2.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section5.3.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section5.4.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section5.5.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section5.6.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section5.7.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section6.1.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section6.2.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section6.3.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section6.4.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section6.5.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section6.6.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section7.1.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section7.2.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section7.4.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section7.5.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section8.1.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section8.2.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section8.3.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section8.4.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section9.1.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section9.2.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section9.3.json
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section99.1.json
Labels: Private Beta

#244 APR-1359 - Update copy for PageId 200
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section1.4.json
Labels: Superbranch

#252 APR-1193 Removing pages from 9.3
  src/SFA.DAS.QnA.Database/projects/roatp/sections/section9.3.json
Labels: Ready for Release

#251 Optimize SetStatusOfAllPagesBasedOnUpdatedQuestionTags
  src/SFA.DAS.QnA.Application/Commands/ResetPageAnswers/ResetPageAnswersHandler.cs
  src/SFA.DAS.QnA.Application/Commands/SetPageAnswers/SetAnswersBase.cs
  src/SFA.DAS.QnA.Application/Commands/SetPageAnswers/SetPageAnswersHandler.cs
Labels: Requires testing
